version: '3.0'

services:
  dev_db:
    image: 'mysql:latest'
    container_name: 'lendsqr_dev_db'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lendsqr
      - MYSQL_USER=dev_user
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - lendsqr_dev_vol:/var/lib/data

  test_db:
    image: 'mysql:latest'
    container_name: 'lendsqr_test_db'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lendsqr
      - MYSQL_USER=test_user
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - lendsqr_test_vol:/var/lib/data

volumes:
  lendsqr_dev_vol:
  lendsqr_test_vol:
